title: The Microstructure Exchange
site:
  description: Something
  title: The Microstructure Exchange

# theme: jekyll-theme-cayman
github: 
  repository_url: https://github.com/cpfiffer/microstructure.exchange
  repository_name: microstructure.exchange
  owner_url: https://github.com/cpfiffer
  owner_name: Cameron Pfiffer

speaker-info:
  speaker-name: "Paige Rowberry (University of Utah)"
  speaker-paper: "Does Market Fragmentation Improve Price Efficiency?"
  coauthors: "Jonathan Brogaard (University of Utah) and Anne Haubo Dyhrberg (University of Delaware)"
  speaker-date: "May 26, 11 a.m. (New York time)"
  #paper-link: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5186551"
  paper-link: "papers/Brogaard, Dyhrberg, Rowberry.pdf" # If you have a file instead
  webinar-link: "https://us06web.zoom.us/j/84504721258?pwd=I2cR9GtVjSa0myOQKYdxRTvQ1PHENW.1"
  # discussant: "Michael Noe (Eurex), Amit Goyal (SFI/Lausanne), and Eric Uhlmann (INSEAD)"
  # slides-link: /slides/RobinhoodSlides_TME.pdf
  abstract: "Chen and Duffie (2021) argue that market fragmentation can improve price efficiency by enabling traders to split their orders across venues, reducing their overall price impact, making their trading more aggressive. Testing this theory in equity markets is difficult due to regulatory requirements that distort market independence. The cryptocurrency marketplace provides an ideal setting given its lack of regulatory interference. Taking advantage of sudden and unexpected changes in coin listings, we use a difference-in-difference identification strategy to show that fragmentation improves price efficiency, consistent with Chen and Duffie (2021). The implications for the role of fragmentation are essential for improving market quality and investor welfare."
