title: The Microstructure Exchange
site:
  description: Something
  title: The Microstructure Exchange

# theme: jekyll-theme-cayman
github: 
  repository_url: https://github.com/cpfiffer/microstructure.exchange
  repository_name: microstructure.exchange
  owner_url: https://github.com/cpfiffer
  owner_name: Cameron Pfiffer

speaker-info:
  speaker-name: "Farshid Abdi (Texas A&M)"
  speaker-paper: "Overnight Corporate Bond Trading"
  coauthors: "Marco Rossi (Texas A&M) and Botao Wu (CUHK)"
  speaker-date: "Sept 15, 11 a.m. (New York time)"
  paper-link: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7198520"
  #paper-link: "papers/Brogaard, Dyhrberg, Rowberry.pdf" # If you have a file instead
  webinar-link: "https://us06web.zoom.us/j/89390179642?pwd=MAx9kM3S03Vx7FqLCwEL2zke6HFgPt.1"
  # discussant: "Michael Noe (Eurex), Amit Goyal (SFI/Lausanne), and Eric Uhlmann (INSEAD)"
  # slides-link: /slides/RobinhoodSlides_TME.pdf
  abstract: "Corporate bond trades executed between 6:30 p.m. and 8:00 a.m. (ET) are not publicly disseminated until after TRACE reopens, generally between 8:00 and 8:15 a.m., creating a recurring interval of delayed post-trade transparency. Using enhanced TRACE data, we study how this temporary opacity affects trading and price discovery in the corporate bond market. Overnight trades are substantially larger than intraday trades and contribute disproportionately to price discovery. Overnight order imbalances predict future returns for both the same bond and other bonds issued by the same firm, indicating that overnight trades contain issuer-level private information. The price impact of overnight trades is significantly stronger and more persistent than that of intraday trades. Overnight activity is also more concentrated among large dealers and associated with higher dealer spreads and worse receiver outcomes. Finally, TRACE dissemination expansions increase overnight trading activity, suggesting that informed traders strategically shift trading toward periods with delayed disclosure."
